
FROM tomcat
LABEL name="antsdouble"
# 删除
RUN rm -fr /usr/local/tomcat/webapps/ROOT/*
# 复制
COPY index.jsp /usr/local/tomcat/webapps/ROOT

WORKDIR /usr/local/tomcat/webapps/ROOT

WORKDIR /usr/local/tomcat

EXPOSE 8080